import type { Lot } from './types'

const hour = 60 * 60 * 1000

function lot(partial: Lot): Lot {
  return partial
}

export const SEED_LOTS: Lot[] = [
  lot({
    id: 'LB-24081',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'iPhone 15 Pro',
    capacity: '256GB',
    color: 'Natural Titanium',
    grade: 'A',
    battery: 91,
    qty: 1,
    startPrice: 620,
    currentPrice: 648,
    bidCount: 14,
    endsAt: Date.now() + 0.35 * hour,
    description: 'Minor hairlines on frame. Face ID OK. Original box not included.',
    accent: '#8a8d91',
  }),
  lot({
    id: 'LB-24082',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Samsung',
    model: 'Galaxy S24 Ultra',
    capacity: '512GB',
    color: 'Titanium Black',
    grade: 'S',
    battery: 97,
    qty: 1,
    startPrice: 710,
    currentPrice: 736,
    bidCount: 9,
    endsAt: Date.now() + 0.9 * hour,
    description: 'Like new. S Pen included. Dual SIM tray.',
    accent: '#1c1c1c',
  }),
  lot({
    id: 'LB-24083',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'iPhone 14',
    capacity: '128GB',
    color: 'Midnight',
    grade: 'B',
    battery: 86,
    qty: 4,
    startPrice: 280,
    currentPrice: 305,
    bidCount: 22,
    endsAt: Date.now() + 1.4 * hour,
    description: 'Light screen wear. Rear glass intact. IMEI clean.',
    accent: '#1a2330',
  }),
  lot({
    id: 'LB-24084',
    channel: 'auction',
    auctionType: 'sealed',
    manufacturer: 'Google',
    model: 'Pixel 8 Pro',
    capacity: '256GB',
    color: 'Obsidian',
    grade: 'A',
    battery: 93,
    qty: 2,
    startPrice: 340,
    currentPrice: 340,
    bidCount: 6,
    endsAt: Date.now() + 18 * hour,
    description: 'Sealed-bid lot. Highest bid wins. Status hidden until close.',
    accent: '#2b2b2b',
  }),
  lot({
    id: 'LB-24085',
    channel: 'auction',
    auctionType: 'hybrid',
    manufacturer: 'Apple',
    model: 'iPad Air 5',
    capacity: '256GB',
    color: 'Blue',
    grade: 'A',
    battery: 94,
    qty: 8,
    startPrice: 310,
    currentPrice: 328,
    bidCount: 11,
    endsAt: Date.now() + 6 * hour,
    description: 'Multi-unit hybrid. Live phase now; extra sealed stage after close.',
    accent: '#3d6fb8',
  }),
  lot({
    id: 'LB-24086',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'MacBook Air M2',
    capacity: '16/512',
    color: 'Starlight',
    grade: 'A',
    battery: 89,
    qty: 1,
    startPrice: 620,
    currentPrice: 655,
    bidCount: 7,
    endsAt: Date.now() + 2.2 * hour,
    description: 'Keyboard clean. Cycle count 214. Charger included.',
    accent: '#e8d9c4',
  }),
  lot({
    id: 'LB-24087',
    channel: 'auction',
    auctionType: 'sealed',
    manufacturer: 'Sony',
    model: 'Xperia 1 V',
    capacity: '256GB',
    color: 'Black',
    grade: 'B',
    battery: 88,
    qty: 3,
    startPrice: 210,
    currentPrice: 210,
    bidCount: 4,
    endsAt: Date.now() + 30 * hour,
    description: 'Camera glass micro-scratch. 5G unlocked.',
    accent: '#111',
  }),
  lot({
    id: 'LB-24088',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S9',
    capacity: '256GB',
    color: 'Graphite',
    grade: 'S',
    battery: 96,
    qty: 2,
    startPrice: 390,
    currentPrice: 401,
    bidCount: 5,
    endsAt: Date.now() + 0.55 * hour,
    description: 'Includes keyboard cover. Grade S cosmetic.',
    accent: '#3a3a3a',
  }),
  lot({
    id: 'MP-11021',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'iPhone 13',
    capacity: '128GB',
    color: 'Starlight',
    grade: 'A',
    battery: 90,
    qty: 12,
    startPrice: 245,
    currentPrice: 245,
    buyNowPrice: 245,
    bidCount: 0,
    endsAt: Date.now() + 120 * hour,
    description: 'Fixed-price wholesale. Mix of carriers, all IMEI clean.',
    accent: '#f3ead8',
  }),
  lot({
    id: 'MP-11022',
    channel: 'marketplace',
    manufacturer: 'Samsung',
    model: 'Galaxy A54',
    capacity: '128GB',
    color: 'Awesome Lime',
    grade: 'B',
    battery: 87,
    qty: 20,
    startPrice: 98,
    currentPrice: 98,
    buyNowPrice: 98,
    bidCount: 0,
    endsAt: Date.now() + 96 * hour,
    description: 'High-volume lot. Light housing wear. Ready to ship.',
    accent: '#c6e86a',
  }),
  lot({
    id: 'MP-11023',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'Watch Series 9',
    capacity: '45mm GPS',
    color: 'Midnight',
    grade: 'S',
    battery: 95,
    qty: 6,
    startPrice: 185,
    currentPrice: 185,
    buyNowPrice: 185,
    bidCount: 0,
    endsAt: Date.now() + 72 * hour,
    description: 'Sport band included. Activation lock removed.',
    accent: '#1b2430',
  }),
  lot({
    id: 'MP-11024',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'iPhone 15',
    capacity: '128GB',
    color: 'Blue',
    grade: 'A',
    battery: 92,
    qty: 5,
    startPrice: 430,
    currentPrice: 430,
    buyNowPrice: 430,
    bidCount: 0,
    endsAt: Date.now() + 48 * hour,
    description: 'Take-all available. USB-C, original battery health 92%+.',
    accent: '#4a7ec8',
  }),
  lot({
    id: 'LB-24089',
    channel: 'auction',
    auctionType: 'hybrid',
    manufacturer: 'Apple',
    model: 'iPhone 12',
    capacity: '64GB',
    color: 'Red',
    grade: 'C',
    battery: 81,
    qty: 15,
    startPrice: 95,
    currentPrice: 108,
    bidCount: 18,
    endsAt: Date.now() + 4 * hour,
    description: 'Housing dings. Screens tested. Good for parts/refurb.',
    accent: '#c0392b',
  }),
  lot({
    id: 'LB-24090',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Google',
    model: 'Pixel 9',
    capacity: '128GB',
    color: 'Porcelain',
    grade: 'S',
    battery: 99,
    qty: 1,
    startPrice: 420,
    currentPrice: 438,
    bidCount: 8,
    endsAt: Date.now() + 3.1 * hour,
    description: 'Open-box. Full retail accessories.',
    accent: '#efe8de',
  }),
]

export const DEMO_USER = {
  accountId: 'DEMO-1001',
  password: 'livebid',
  company: 'Northstar Mobile Ltd.',
  email: 'buyer@northstar.example',
  role: 'member' as const,
}

export const ADMIN_USER = {
  accountId: 'ADMIN-0001',
  password: 'admin',
  company: 'LiveBid Operations',
  email: 'ops@livebid.example',
  role: 'admin' as const,
}
