import { ORIGINS } from './lib/auctionLists'
import type { Account, AuctionType, Lot, SiteSettings } from './types'

export const DEFAULT_SETTINGS: SiteSettings = {
  brandName: 'Equarios',
  brandMark: 'EQ',
  brandLogo: '/equarios-logo.png',
  tagline: 'Global Tech Supply & IT Solutions',
  marketplaceLabel: 'Marketplace',
  showAuctions: true,
  showMarketplace: true,
  showFavourites: true,
  filters: {
    type: true,
    maker: true,
    grade: true,
    capacity: true,
    price: true,
  },
  grades: ['S', 'A', 'B', 'C'],
  auctionTypes: [
    {
      value: 'live',
      label: 'Real-time',
      fillMode: 'live',
      intro: 'Real-time list: last bid per account fills this inventory. You only see your own fill.',
    },
    {
      value: 'sealed',
      label: 'Sealed bid',
      fillMode: 'sealed',
      intro: 'Sealed-bid list: other fills stay hidden until close. Separate catalog from live lots.',
    },
    {
      value: 'hybrid',
      label: 'Hybrid',
      fillMode: 'hybrid',
      intro: 'Hybrid list: live fill now, then a sealed stage. Its own inventory, not mixed with live.',
    },
  ],
  defaultMoq: 0,
  reopenHours: 4,
  extendHours: 2,
  reopenMinutes: 240,
  extendMinutes: 120,
  endingSoonMinutes: 15,
  theme: {
    navy: '#133a8a',
    navy2: '#0d2c6b',
    ink: '#1a1a1a',
    muted: '#5b6570',
    line: '#e6e6e6',
    bg: '#ffffff',
    card: '#ffffff',
    win: '#0f7a3c',
    lose: '#c62828',
    live: '#c4161c',
    font: "'Segoe UI', system-ui, sans-serif",
    radius: '4px',
  },
  features: {
    bidding: true,
    takeAll: true,
    favourites: true,
    confirmBid: true,
    confirmTakeAll: true,
    confirmCart: true,
    confirmCheckout: true,
    confirmPay: true,
    cart: true,
    bots: true,
    register: true,
    forgotPassword: true,
    siteNotice: true,
    endingSoon: true,
  },
  copy: {
    navAuctions: 'Auctions',
    navFavourites: 'Favorites',
    navInvoices: 'Invoice',
    navAccount: 'My Page',
    navAdmin: 'Admin',
    navSuper: 'Super admin',
    signOut: 'Sign out',
    signInTitle: 'Sign in',
    signInButton: 'Sign in',
    signUpTitle: 'Sign up',
    signUpIntro: 'B2B wholesale. New accounts stay pending until super admin approval.',
    signUpButton: 'Create account',
    pendingApproval: 'Application submitted. A super admin must approve this account before you can sign in.',
    auctionsTitle: 'Live auctions',
    auctionsIntro:
      'Place a bid for the pcs you want. You only see how many pcs you are winning — other clients’ fills stay private.',
    marketTitle: 'Marketplace',
    marketIntro: 'Fixed wholesale prices. Add to cart on this page — no extra listing screen.',
    favouritesTitle: 'Favourites',
    favouritesIntro:
      'Favourites in one place. Bid auction lots here, or add marketplace lots to cart — no need to leave this page.',
    invoicesTitle: 'Invoices',
    invoicesIntro:
      'Pay your invoice, then upload the receipt. It stays unpaid until both an admin and super admin accept.',
    accountTitle: 'My Page',
    accountIntro: 'Bid history, marketplace orders, invoices, and account settings.',
    searchAuctions: 'Search model, SKU, maker, lot ID',
    searchMarket: 'Search model, SKU, maker, lot ID',
    emptyFilters: 'No lots match those filters.',
    emptyFavourites: 'Nothing favourited yet.',
    emptyCart: 'Cart is empty. Choose desired qty and add to cart.',
    emptyInvoices: 'No invoices yet. Buy a marketplace lot to generate one.',
    btnBid: 'Bid',
    btnTakeAll: 'Take all',
    btnAddCart: 'Add to cart',
    btnCheckout: 'Checkout',
    btnPay: 'I have paid',
    btnAccept: 'Accept',
    btnDecline: 'Decline',
    btnResubmitPay: 'Upload new receipt',
    btnRemove: 'Remove',
    btnPhotos: 'Photos',
    btnForgot: 'Forgot password?',
    btnConfirm: 'Confirm',
    btnCancel: 'Cancel',
    confirmBidTitle: 'Confirm this bid?',
    confirmBidBody: 'Check qty and price, then confirm.',
    confirmTakeAllTitle: 'Take all remaining pcs?',
    confirmTakeAllBody: 'This sets your desired qty to the full lot ({n} pcs). You still need to bid.',
    confirmCartTitle: 'Add this to cart?',
    confirmCartBody: 'Check qty and price, then confirm.',
    confirmCheckoutTitle: 'Confirm checkout?',
    confirmCheckoutBody: 'This creates unpaid invoices for every item in the cart. Pay from Invoices.',
    confirmPayTitle: 'Have you already made payment?',
    confirmPayBody:
      'Only submit if the transfer is already sent. Upload the receipt. Admin and super admin both must accept before this invoice is marked paid.',
    payAckLabel: 'I confirm I have already paid this invoice.',
    receiptLabel: 'Payment receipt (image or PDF)',
    payWaiting: 'Receipt submitted. Waiting for admin and super admin to accept.',
    payNeedAdmin: 'Waiting for admin',
    payNeedSuper: 'Waiting for super admin',
    payDeclinedNote: 'Payment was declined. Upload a new receipt if you have paid.',
    confirmForgotTitle: 'Reset password',
    confirmForgotBody: 'Ask super admin to set a new password on the Accounts tab. This demo cannot email a reset.',
    favAdd: 'Favourite',
    favRemove: 'Favourited',
    closed: 'Closed',
    noMoq: 'No MOQ',
    cartTitle: 'Cart',
    emptyMarket: 'No marketplace listings right now.',
    siteNotice: 'Invoices are due within 48 hours. Unpaid lots may be reopened to other buyers.',
    endingSoon: 'Closing soon — under {n} min left.',
    okAddedCart: 'Added {n} pcs',
    okCheckout: 'Checkout complete. Invoice created.',
    okBid: 'Confirmed {qty} pcs @ {price}',
    okPaid: 'Invoice marked paid after admin and super admin both accepted.',
    okPaySubmitted: 'Receipt sent for admin and super admin approval.',
    warnReceipt: 'Upload a payment receipt (image or PDF, max 3 MB).',
    warnPayAck: 'Tick the box to confirm you have already paid.',
    warnMoq: 'MOQ for this model is {n} pcs.',
    warnQty: 'Desired qty must be a whole number of 1 or more.',
    warnOverQty: 'Desired qty cannot exceed total pcs ({n}).',
    warnMinPrice: 'Minimum price per pc is {price}.',
    warnNoBid: 'Bidding is turned off by super admin.',
    warnPending: 'This account is waiting for super admin approval.',
    warnDisabled: 'This account is disabled. Contact super admin.',
    warnClosed: 'This auction has closed.',
    warnCart: 'Cart is turned off by super admin.',
    warnLogin: 'Invalid email, account ID, or password.',
    warnRegister: 'Fill all fields. Password must be at least 6 characters.',
    warnAccountTaken: 'That account ID is already registered.',
    warnLotMissing: 'Lot not found.',
    warnListingGone: 'Listing {id} is no longer available.',
  },
  icons: {
    favourite: '♥',
  },
}

const hour = 60 * 60 * 1000

function lot(partial: Lot): Lot {
  const n = Number((partial.id.match(/\d+/) || ['0'])[0])
  return { origin: ORIGINS[n % ORIGINS.length], ...partial }
}

const CORE_LOTS: Lot[] = [
  lot({
    id: 'LB-24081',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'iPhone 15 Pro',
    modelNumber: 'A3102',
    capacity: '256GB',
    color: 'Natural Titanium',
    grade: 'A',
    battery: 91,
    qty: 1,
    startPrice: 620,
    currentPrice: 648,
    bidCount: 14,
    endsAt: Date.now() + 0.35 * hour,
    description: 'EU/UK model A3102. Minor hairlines on frame. Face ID OK. Original box not included.',
    accent: '#8a8d91',
  }),
  lot({
    id: 'LB-24082',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Samsung',
    model: 'Galaxy S24 Ultra',
    modelNumber: 'SM-S928B',
    capacity: '512GB',
    color: 'Titanium Black',
    grade: 'S',
    battery: 97,
    qty: 1,
    startPrice: 710,
    currentPrice: 736,
    bidCount: 9,
    endsAt: Date.now() + 0.9 * hour,
    description: 'International model SM-S928B (not US SM-S928U). Like new. S Pen included. Dual SIM tray.',
    accent: '#1c1c1c',
  }),
  lot({
    id: 'LB-24083',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'iPhone 14',
    modelNumber: 'A2882',
    capacity: '128GB',
    color: 'Midnight',
    grade: 'B',
    battery: 86,
    qty: 10000,
    moq: 20,
    startPrice: 280,
    currentPrice: 305,
    bidCount: 22,
    endsAt: Date.now() + 1.4 * hour,
    description: 'Light screen wear. Rear glass intact. IMEI clean.',
    accent: '#1a2330',
  }),
  lot({
    id: 'LB-24084',
    channel: 'auction',
    auctionType: 'sealed',
    manufacturer: 'Google',
    model: 'Pixel 8 Pro',
    modelNumber: 'GP4BC',
    capacity: '256GB',
    color: 'Obsidian',
    grade: 'A',
    battery: 93,
    qty: 10000,
    moq: 30,
    startPrice: 340,
    currentPrice: 340,
    bidCount: 6,
    endsAt: Date.now() + 18 * hour,
    description: 'Sealed-bid lot. Highest bid wins. Status hidden until close.',
    accent: '#2b2b2b',
  }),
  lot({
    id: 'LB-24085',
    channel: 'auction',
    auctionType: 'hybrid',
    manufacturer: 'Apple',
    model: 'iPad Air 5',
    modelNumber: 'MM9F3LL/A',
    capacity: '256GB',
    color: 'Blue',
    grade: 'A',
    battery: 94,
    qty: 10000,
    moq: 40,
    startPrice: 310,
    currentPrice: 328,
    bidCount: 11,
    endsAt: Date.now() + 6 * hour,
    description: 'Multi-unit hybrid. Live phase now; extra sealed stage after close.',
    accent: '#3d6fb8',
  }),
  lot({
    id: 'LB-24086',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'MacBook Air M2',
    modelNumber: 'MLXY3LL/A',
    capacity: '16/512',
    color: 'Starlight',
    grade: 'A',
    battery: 89,
    qty: 1,
    startPrice: 620,
    currentPrice: 655,
    bidCount: 7,
    endsAt: Date.now() + 2.2 * hour,
    description: 'Keyboard clean. Cycle count 214. Charger included.',
    accent: '#e8d9c4',
  }),
  lot({
    id: 'LB-24087',
    channel: 'auction',
    auctionType: 'sealed',
    manufacturer: 'Sony',
    model: 'Xperia 1 V',
    modelNumber: 'XQ-DQ54',
    capacity: '256GB',
    color: 'Black',
    grade: 'B',
    battery: 88,
    qty: 10000,
    startPrice: 210,
    currentPrice: 210,
    bidCount: 4,
    endsAt: Date.now() + 30 * hour,
    description: 'Camera glass micro-scratch. 5G unlocked.',
    accent: '#111',
  }),
  lot({
    id: 'LB-24088',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S9',
    modelNumber: 'SM-X710',
    capacity: '256GB',
    color: 'Graphite',
    grade: 'S',
    battery: 96,
    qty: 10000,
    moq: 20,
    startPrice: 390,
    currentPrice: 401,
    bidCount: 5,
    endsAt: Date.now() + 0.55 * hour,
    description: 'Includes keyboard cover. Grade S cosmetic.',
    accent: '#3a3a3a',
  }),
  lot({
    id: 'MP-11021',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'iPhone 13',
    modelNumber: 'A2633',
    capacity: '128GB',
    color: 'Starlight',
    grade: 'A',
    battery: 90,
    qty: 10000,
    moq: 20,
    startPrice: 245,
    currentPrice: 245,
    buyNowPrice: 245,
    bidCount: 0,
    endsAt: Date.now() + 120 * hour,
    description: 'Fixed-price wholesale. Mix of carriers, all IMEI clean.',
    accent: '#f3ead8',
  }),
  lot({
    id: 'MP-11022',
    channel: 'marketplace',
    manufacturer: 'Samsung',
    model: 'Galaxy A54',
    modelNumber: 'SM-A546B',
    capacity: '128GB',
    color: 'Awesome Lime',
    grade: 'B',
    battery: 87,
    qty: 10000,
    moq: 30,
    startPrice: 98,
    currentPrice: 98,
    buyNowPrice: 98,
    bidCount: 0,
    endsAt: Date.now() + 96 * hour,
    description: 'High-volume lot. Light housing wear. Ready to ship.',
    accent: '#c6e86a',
  }),
  lot({
    id: 'MP-11023',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'Watch Series 9',
    modelNumber: 'MR9U3LL/A',
    capacity: '45mm GPS',
    color: 'Midnight',
    grade: 'S',
    battery: 95,
    qty: 10000,
    startPrice: 185,
    currentPrice: 185,
    buyNowPrice: 185,
    bidCount: 0,
    endsAt: Date.now() + 72 * hour,
    description: 'Sport band included. Activation lock removed.',
    accent: '#1b2430',
  }),
  lot({
    id: 'MP-11024',
    channel: 'marketplace',
    manufacturer: 'Apple',
    model: 'iPhone 15',
    modelNumber: 'A3090',
    capacity: '128GB',
    color: 'Blue',
    grade: 'A',
    battery: 92,
    qty: 10000,
    moq: 20,
    startPrice: 430,
    currentPrice: 430,
    buyNowPrice: 430,
    bidCount: 0,
    endsAt: Date.now() + 48 * hour,
    description: 'Take-all available. USB-C, original battery health 92%+.',
    accent: '#4a7ec8',
  }),
  lot({
    id: 'LB-24089',
    channel: 'auction',
    auctionType: 'hybrid',
    manufacturer: 'Apple',
    model: 'iPhone 12',
    modelNumber: 'A2403',
    capacity: '64GB',
    color: 'Red',
    grade: 'C',
    battery: 81,
    qty: 10000,
    moq: 40,
    startPrice: 95,
    currentPrice: 108,
    bidCount: 18,
    endsAt: Date.now() + 4 * hour,
    description: 'Housing dings. Screens tested. Good for parts/refurb.',
    accent: '#c0392b',
  }),
  lot({
    id: 'LB-24090',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Google',
    model: 'Pixel 9',
    modelNumber: 'G2YBB',
    capacity: '128GB',
    color: 'Porcelain',
    grade: 'S',
    battery: 99,
    qty: 1,
    startPrice: 420,
    currentPrice: 438,
    bidCount: 8,
    endsAt: Date.now() + 3.1 * hour,
    description: 'Open-box. Full retail accessories.',
    accent: '#efe8de',
  }),
  lot({
    id: 'LB-24091',
    channel: 'auction',
    auctionType: 'live',
    manufacturer: 'Apple',
    model: 'iPhone 15 Pro',
    modelNumber: 'A2848',
    capacity: '256GB',
    color: 'Blue Titanium',
    grade: 'A',
    battery: 93,
    qty: 10000,
    moq: 20,
    startPrice: 610,
    currentPrice: 632,
    bidCount: 6,
    endsAt: Date.now() + 1.1 * hour,
    description: 'US model A2848 (not EU A3102). Light frame wear. Face ID OK.',
    accent: '#3d5a80',
  }),
]

function moreInventory(): Lot[] {
  const bases = CORE_LOTS.filter((l) => l.channel === 'auction')
  const types: AuctionType[] = ['live', 'sealed', 'hybrid']
  const extra: Lot[] = []
  let n = 24201
  for (const auctionType of types) {
    for (let i = 0; i < 16; i++) {
      const base = bases[i % bases.length]
      extra.push(
        lot({
          ...base,
          id: `LB-${n++}`,
          auctionType,
          origin: ORIGINS[i % ORIGINS.length],
          qty: base.qty > 1 ? 400 + i * 80 : 1,
          moq: base.qty > 1 ? Math.max(base.moq || 20, 10) : undefined,
          currentPrice: base.startPrice + i * 3,
          bidCount: i % 9,
          endsAt:
            Date.now() +
            (auctionType === 'sealed' ? 8 + i : auctionType === 'hybrid' ? 3 + i * 0.4 : 0.6 + i * 0.35) *
              hour,
          description: `${base.description} · ${ORIGINS[i % ORIGINS.length]} origin catalog.`,
        }),
      )
    }
  }
  return extra
}

export const SEED_LOTS: Lot[] = [...CORE_LOTS, ...moreInventory()]

export const DEMO_USER: Account = {
  accountId: 'DEMO-1001',
  password: 'livebid',
  company: 'equarios corporation limited',
  email: 'buyer@northstar.example',
  role: 'member',
  status: 'active',
}

export const ADMIN_USER: Account = {
  accountId: 'ADMIN-0001',
  password: 'admin',
  company: 'Equarios Ops',
  email: 'ops@livebid.example',
  role: 'admin',
  status: 'active',
}

export const SUPER_USER: Account = {
  accountId: 'SUPER-0001',
  password: 'super',
  company: 'equarios corporation limited',
  email: 'super@livebid.example',
  role: 'superadmin',
  status: 'active',
}

export const SEED_ACCOUNTS: Account[] = [SUPER_USER, ADMIN_USER, DEMO_USER]
